# Generated by Django 2.2 on 2020-03-09 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 9, 1, 50, 43, 595867, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
