# Generated by Django 2.2 on 2020-03-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_consulta_data_agendamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='data_agendamento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data de agandamento'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horario',
            field=models.TimeField(verbose_name='horário'),
        ),
    ]
