# Generated by Django 2.2 on 2020-03-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['dia'], 'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
    ]
