# Generated by Django 2.2 on 2020-02-26 13:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Digite a especialidade', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Digite a nome do médico', max_length=100)),
                ('crm', models.CharField(help_text='Digite o CRM do médico', max_length=7, unique=True)),
                ('email', models.EmailField(help_text='Digite o E-mail do médico', max_length=254, verbose_name='E-mail')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Digite o telefone do médico', max_length=128, region=None)),
                ('especialidade', models.ForeignKey(help_text='Selecione a especialidade do médico', on_delete=django.db.models.deletion.PROTECT, to='agendamento.Especialidade')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField()),
                ('horarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.Horarios')),
                ('medico', models.ForeignKey(help_text='Selecione um médico', on_delete=django.db.models.deletion.PROTECT, to='agendamento.Medico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'unique_together': {('medico', 'dia')},
            },
        ),
    ]
