# Generated by Django 2.2 on 2020-03-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_auto_20200304_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horarios',
            field=models.ManyToManyField(help_text='Escolha os Horários', to='agendamento.Horario', verbose_name='horários'),
        ),
    ]
